Para la notebook de "Inferencia Ecológica para Evolución del Voto", podemos estructurar el trabajo en varias secciones para realizar un análisis completo y sistemático. Aquí te propongo una estructura posible para la notebook:

### 1. Introducción y Objetivos
   - Breve descripción de lo que es la inferencia ecológica y por qué es relevante para el análisis de datos electorales.
   - Definición de los objetivos específicos de la notebook.

### 2. Preparación de Datos
   - **Carga de Datos**: Importar los datos electorales necesarios para el análisis.
   - **Limpieza de Datos**: Verificar la calidad de los datos y realizar cualquier limpieza o transformación necesaria.
   - **Verificación de Datos**: Asegurarse de que los datos están correctamente estructurados y listos para el análisis.

### 3. Análisis Exploratorio de Datos (EDA)
   - **Resumen Estadístico**: Proporcionar estadísticas descriptivas de los datos.
   - **Visualización de Datos**: Crear gráficos para visualizar las tendencias y patrones en los datos.
   - **Identificación de Tendencias**: Observar cómo los votos para los diferentes partidos o candidatos han evolucionado a lo largo del tiempo.

### 4. Modelado y Inferencia
   - **Selección de Modelo**: Elegir el modelo o los modelos estadísticos apropiados para la inferencia ecológica.
   - **Ajuste de Modelo**: Ajustar el modelo a los datos.
   - **Evaluación de Modelo**: Evaluar la precisión y validez del modelo.
   - **Inferencias**: Realizar inferencias sobre la evolución del voto y los factores que pueden haber contribuido a los cambios observados.

### 5. Interpretación de Resultados
   - **Análisis de Resultados**: Interpretar los resultados del modelo y las inferencias realizadas.
   - **Identificación de Factores Clave**: Destacar los factores que parecen haber tenido un impacto significativo en la evolución del voto.

### 6. Visualización de Resultados
   - Crear visualizaciones para presentar los resultados de una manera clara y comprensible.

### 7. Conclusiones y Recomendaciones
   - Resumir los hallazgos clave.
   - Proporcionar recomendaciones basadas en los resultados.

### 8. Referencias
   - Citar cualquier fuente o recurso utilizado en la notebook.

### Herramientas y Bibliotecas Sugeridas
   - Pandas para la manipulación y análisis de datos.
   - Matplotlib y Seaborn para la visualización de datos.
   - Scikit-learn o Statsmodels para el modelado estadístico.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

In [ ]:
path_datos = '/content/drive/My Drive/electoral/datos'
# path_datosBD = './../datos/BD'


### 2. Preparación de Datos
   - **Carga de Datos**: Importar los datos electorales necesarios para el análisis.

In [ ]:
import pandas as pd

In [ ]:

df_mesas = pd.read_csv(path_datos+'/BD/mesas_table.csv')
df_mesas_18 = pd.read_csv(path_datos+'/BD2/mesas_table.csv')

In [ ]:
mesas23 = pd.concat([df_mesas.loc[df_mesas.eleccion_id == 17], df_mesas_18])


### 2. Preparación de Datos

#### Carga de Datos:
- Se cargan los datos de votación de diferentes elecciones y otros archivos relacionados con la elección, como listas de agrupaciones y claves de departamentos.
- Se concatenan los DataFrames de diferentes elecciones y se filtran según los cargos electivos.

In [ ]:
import pandas as pd
# # ----- Data Loading -----

# Define the path to your data
# path_datosBD = "./your/data/path"
path_datosBD = '/content/drive/My Drive/electoral/datos/BD'

# Define the cargo IDs you are interested in
cargo_ids = [1, 3, 4]

# List of election files
election_files = ['votos_eleccion_17_table.csv', 'votos_eleccion_18_table.csv'] # df23PASO, df23GRAL

# # Load and filter the data in a single line
# df = pd.concat([pd.read_csv(f"{path_datosBD}/{file_name}").query("cargo_id in @cargo_ids") for file_name in election_files], axis=0)
# df = df.drop(['agrupacion_nombre'], axis = 1)

In [ ]:
df = pd.concat([pd.read_csv(f"{path_datos}/BD/{file_name}").query("cargo_id in @cargo_ids") for file_name in election_files], axis=0)
df.groupby('eleccion_id').votos_cantidad.sum()

<ipython-input-7-13145e49d6ba>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat([pd.read_csv(f"{path_datosBD}/{file_name}").query("cargo_id in @cargo_ids") for file_name in election_files], axis=0)
<ipython-input-7-13145e49d6ba>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat([pd.read_csv(f"{path_datosBD}/{file_name}").query("cargo_id in @cargo_ids") for file_name in election_files], axis=0)

eleccion_id
17     56939512
18    121537714
Name: votos_cantidad, dtype: int64

In [ ]:
df17 = pd.read_csv(f"{path_datosBD}/{'votos_eleccion_17_table.csv'}").query("cargo_id in @cargo_ids")

<ipython-input-10-7654ecc7a009>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df17 = pd.read_csv(f"{path_datosBD}/{'votos_eleccion_17_table.csv'}").query("cargo_id in @cargo_ids")

In [ ]:
df18 = pd.read_csv(f"{path_datosBD}/{'votos_eleccion_18_table.csv'}").query("cargo_id in @cargo_ids")

<ipython-input-11-61960a9ef02b>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df18 = pd.read_csv(f"{path_datosBD}/{'votos_eleccion_18_table.csv'}").query("cargo_id in @cargo_ids")

In [ ]:
df17.groupby(['cargo_id', 'votos_tipo']).votos_cantidad.sum()

cargo_id  votos_tipo
1         BLANCO         1148342
          COMANDO          21758
          IMPUGNADO         4000
          NULO            293041
          POSITIVO      22539543
          RECURRIDO        10092
3         BLANCO         2482954
          COMANDO          23403
          IMPUGNADO         4180
          NULO            278168
          POSITIVO      20704629
          RECURRIDO         8808
4         BLANCO         1040259
          COMANDO          19328
          IMPUGNADO         6484
          NULO             78988
          POSITIVO       8272836
          RECURRIDO         2699
Name: votos_cantidad, dtype: int64

In [ ]:
df17.groupby(['cargo_id', 'votos_tipo']).nunique()#.sum()

                     distrito_id  seccionprovincial_id  seccion_id  \
cargo_id votos_tipo
1        BLANCO               24                     9         135
         COMANDO              24                     9         135
         IMPUGNADO            24                     9         135
         NULO                 24                     9         135
         POSITIVO             24                     9         135
         RECURRIDO            24                     9         135
3        BLANCO               24                     9         135
         COMANDO              24                     9         135
         IMPUGNADO            24                     9         135
         NULO                 24                     9         135
         POSITIVO             24                     9         135
         RECURRIDO            24                     9         135
4        BLANCO                3                     9         135
         COMANDO               3                     9         135
         IMPUGNADO             3                     9         135
         NULO                  3                     9         135
         POSITIVO              3                     9         135
         RECURRIDO             3                     9         135

                     circuito_id  mesa_id  agrupacion_id  agrupacion_nombre  \
cargo_id votos_tipo
1        BLANCO             2537     9097              1                  0
         COMANDO            2537     9097              1                  0
         IMPUGNADO          2537     9097              1                  0
         NULO               2537     9097              1                  0
         POSITIVO           2537     9097             15                 15
         RECURRIDO          2537     9097              1                  0
3        BLANCO             2563     9097              1                  0
         COMANDO            2563     9097              1                  0
         IMPUGNADO          2563     9097              1                  0
         NULO               2563     9097              1                  0
         POSITIVO           2563     9097            106                 93
         RECURRIDO          2563     9097              1                  0
4        BLANCO             1118     3274              1                  0
         COMANDO            1118     3274              1                  0
         IMPUGNADO          1118     3274              1                  0
         NULO               1118     3274              1                  0
         POSITIVO           1118     3274             33                 28
         RECURRIDO          1118     3274              1                  0

                     lista_numero  votos_cantidad  eleccion_id
cargo_id votos_tipo
1        BLANCO                 1             140            1
         COMANDO                1              85            1
         IMPUGNADO              1              23            1
         NULO                   1              61            1
         POSITIVO              27             218            1
         RECURRIDO              1              48            1
3        BLANCO                 1             258            1
         COMANDO                1              96            1
         IMPUGNADO              1              27            1
         NULO                   1              95            1
         POSITIVO             188             212            1
         RECURRIDO              1              48            1
4        BLANCO                 1             164            1
         COMANDO                1              77            1
         IMPUGNADO              1              55            1
         NULO                   1              66            1
         POSITIVO              44             190            1
         RECURRIDO              1              21            1

In [ ]:
df17.loc[(df17.cargo_id == 3) & (df17.votos_tipo == 'POSITIVO')].groupby('agrupacion_id').votos_cantidad.sum().sort_values().tail(15)/1e6

agrupacion_id
517    0.205869
522    0.226301
182    0.252489
513    0.254825
509    0.273008
231    0.290647
554    0.383654
136    0.503858
505    0.564697
504    0.719849
503    1.633419
501    1.853674
135    2.997147
134    3.436391
132    4.723349
Name: votos_cantidad, dtype: float64

In [ ]:
df18.loc[(df18.cargo_id == 3) & (df18.votos_tipo == 'POSITIVO')].groupby('agrupacion_id').votos_cantidad.sum().sort_values().tail(15)/1e6

agrupacion_id
505       0.564697
210507    0.578409
210501    0.642829
40503     0.675792
504       0.719849
40506     0.746404
10504     0.761015
503       1.633419
501       1.853674
20135     2.327998
20132     2.431634
135       2.997147
134       3.436391
20134     3.993120
132       4.723349
Name: votos_cantidad, dtype: float64

In [ ]:
df18.groupby(['cargo_id', 'votos_tipo']).nunique()#.sum()

                     distrito_id  seccionprovincial_id  seccion_id  \
cargo_id votos_tipo
1        BLANCO               24                     9         135
         COMANDO              24                     9         135
         IMPUGNADO            24                     9         135
         NULO                 24                     9         135
         POSITIVO             24                     9         135
         RECURRIDO            24                     9         135
3        BLANCO               24                     9         135
         COMANDO              24                     9         135
         IMPUGNADO            24                     9         135
         NULO                 24                     9         135
         POSITIVO             24                     9         135
         RECURRIDO            24                     9         135
4        BLANCO                3                     9         135
         COMANDO               3                     9         135
         IMPUGNADO             3                     9         135
         NULO                  3                     9         135
         POSITIVO              3                     9         135
         RECURRIDO             3                     9         135

                     circuito_id  mesa_id  agrupacion_id  lista_numero  \
cargo_id votos_tipo
1        BLANCO             2630     9097              1             1
         COMANDO            2631     9097              1             1
         IMPUGNADO          2631     9097              1             1
         NULO               2630     9097              1             1
         POSITIVO           2630     9097             15            27
         RECURRIDO          2631     9097              1             1
3        BLANCO             2935     9097              1             1
         COMANDO            2935     9097              1             1
         IMPUGNADO          2935     9097              1             1
         NULO               2935     9097              1             1
         POSITIVO           2935     9097            204           188
         RECURRIDO          2935     9097              1             1
4        BLANCO             1118     3274              1             1
         COMANDO            1118     3274              1             1
         IMPUGNADO          1118     3274              1             1
         NULO               1118     3274              1             1
         POSITIVO           1118     3274             40            44
         RECURRIDO          1118     3274              1             1

                     votos_cantidad  eleccion_id
cargo_id votos_tipo
1        BLANCO                 142            1
         COMANDO                 91            1
         IMPUGNADO               27            1
         NULO                    66            1
         POSITIVO               264            1
         RECURRIDO               67            1
3        BLANCO                 259            1
         COMANDO                102            1
         IMPUGNADO               30            1
         NULO                   112            1
         POSITIVO               254            1
         RECURRIDO               65            1
4        BLANCO                 168            1
         COMANDO                 78            1
         IMPUGNADO               71            1
         NULO                    69            1
         POSITIVO               216            1
         RECURRIDO               25            1

In [ ]:
df18.head()

,distrito_id,seccionprovincial_id,seccion_id,circuito_id,mesa_id,cargo_id,agrupacion_id,lista_numero,votos_tipo,votos_cantidad,eleccion_id
2659326,1,0.0,1,000001,1,3,554,3111.0,POSITIVO,71,18
2659327,1,0.0,1,000001,1,3,132,3008.0,POSITIVO,40,18
2659328,1,0.0,1,000001,1,3,132,3007.0,POSITIVO,30,18
2659329,1,0.0,1,000001,1,3,135,3016.0,POSITIVO,41,18
2659330,1,0.0,1,000001,1,3,136,3009.0,POSITIVO,15,18

In [ ]:


# df23PASO = pd.read_csv(path_datosBD + '/votos_eleccion_17_table.csv')
# df23GRAL = pd.read_csv(path_datosBD + '/votos_eleccion_18_table.csv')
# df = pd.concat([df23PASO, df23GRAL], axis=0)
# df = df.loc[(df.cargo_id.isin([1, 3, 4]))]

cargo = pd.read_csv(path_datosBD + '/cargo_tags.csv')
agrup_lista = pd.read_csv(path_datosBD + '/agrupacion_lista_table.csv').drop(['agrupacion_nombre'], axis = 1)
agrup_nombre = pd.read_csv('/content/drive/My Drive/electoral/datos/BD2/agrupacion_nombre_table.csv', dtype={'agrupacion_id': int}) ## agrupacion nombres
claves_dptos = pd.read_csv(path_datosBD + '/claves_dptos_ref.csv')
eleccion_tags = pd.read_csv(path_datosBD + '/eleccion_tags.csv')
prov_nams = pd.read_csv(path_datosBD + '/distrito_table.csv')


#### Limpieza de Datos:
- Se realizan transformaciones en los IDs de agrupación y números de lista para armonizarlos y asegurar consistencia.
- Se limpian y armonizan los nombres de las agrupaciones.

In [ ]:
import pandas as pd

# ----- Function Definitions -----
def harmonize_agrupacion_id(agrupacion_id):
    if pd.isna(agrupacion_id):
        return "000000"
    else:
        try:
            return str(int(float(agrupacion_id))).zfill(6)
        except ValueError:
            return agrupacion_id

def harmonize_agrupacion_names(df, col_name='agrupacion_nombre'):
    """Harmonizes the names of agrupaciones."""
    replacements = {
        'CAMBIEMOS BUENOS AIRES': 'CAMBIEMOS',
        'JUNTOS': 'JUNTOS POR EL CAMBIO'
    }
    df[col_name] = df[col_name].replace(replacements).str.title().str.strip()
    return df

In [ ]:
df.groupby('eleccion_id').votos_cantidad.sum()

In [ ]:

# Agrup Nombre Data Preprocessing
# agrup_nombre['agrupacion_id'] = agrup_nombre['agrupacion_id'].apply(harmonize_agrupacion_id)
merged_data = df.merge(agrup_nombre.drop(['eleccion_id'], axis = 1).drop_duplicates())
merged_data = harmonize_agrupacion_names(merged_data)

In [ ]:
merged_data.groupby('eleccion_id').votos_cantidad.sum()

In [ ]:
merged_data.head()


#### Verificación de Datos:
- Aunque no se muestra explícitamente en el código proporcionado, se asume que las operaciones de fusión, agrupación y transformación de datos forman parte del proceso de verificación de datos para asegurarse de que están estructurados correctamente y listos para el análisis.

In [ ]:
178477226/163013395

In [ ]:
aggregated_data.votos_cantidad.sum()

In [ ]:
# Group and aggregate data
# aggregated_data = merged_data.groupby(['eleccion_id', 'cargo_id', 'agrupacion_nombre', 'lista_numero', 'votos_tipo']).agg({'votos_cantidad': 'sum'}).reset_index()
# aggregated_data = merged_data.groupby(['eleccion_id', 'cargo_id', 'agrupacion_nombre', 'votos_tipo']).agg({'votos_cantidad': 'sum'}).reset_index()
aggregated_data['votos_cantidad_m'] = (aggregated_data['votos_cantidad']/1e6).round(2)
display(aggregated_data.loc[aggregated_data.cargo_id == 1].sort_values('votos_cantidad', ascending = False).set_index(['agrupacion_nombre', 'votos_tipo', 'eleccion_id'])['votos_cantidad_m'].unstack())

## CANTIDAD DE VOTOS.

In [ ]:


# Top N aggregation
N = 20
top_aggregated_data = aggregated_data.groupby(['eleccion_id', 'cargo_id', 'votos_tipo'])\
                                     .apply(lambda x: x.nlargest(N, 'votos_cantidad'))\
                                     .reset_index(drop=True).rename(columns={'votos_cantidad': 'votos_nacional'})
# display(top_aggregated_data)

In [ ]:

# Further transformations on original data
data_copy = merged_data.copy()
data_copy = data_copy.merge(top_aggregated_data, how='left')
data_copy['agrupacion_nombre_'] = data_copy['agrupacion_nombre'].mask(data_copy['votos_nacional'].isnull(), 'Resto')

In [ ]:

# data_aggregated = data_copy.groupby(['distrito_id', 'seccion_id', 'circuito_id', 'mesa_id', 'cargo_id', 'agrupacion_nombre_', 'lista_numero', 'votos_tipo', 'eleccion_id'])\
data_aggregated = data_copy.groupby(['distrito_id', 'seccion_id', 'circuito_id', 'mesa_id', 'cargo_id', 'agrupacion_nombre_', 'votos_tipo', 'eleccion_id'])\
                           .agg({'votos_cantidad': 'sum'}).reset_index()

In [ ]:

# More transformations...
# data_circ = data_aggregated.groupby(['eleccion_id', 'cargo_id', 'agrupacion_nombre_', 'lista_numero', 'votos_tipo', 'distrito_id', 'seccion_id', 'circuito_id'])[['votos_cantidad']].sum()
data_circ = data_aggregated.groupby(['eleccion_id', 'cargo_id', 'agrupacion_nombre_', 'votos_tipo', 'distrito_id', 'seccion_id', 'circuito_id'])[['votos_cantidad']].sum()
data_circ = data_circ.reset_index()
data_circ = data_circ.merge(eleccion_tags).merge(cargo)

In [ ]:

# Group by 'eleccion_tag', 'cargo_tag', and 'in1_& (df.distrito_id == 2)prov', and calculate the sum of 'votos_cantidad', divide for PCT
sum_votes = data_circ.groupby(['eleccion_tag', 'cargo_tag', 'distrito_id', 'seccion_id', 'votos_tipo', 'circuito_id'])['votos_cantidad'].transform('sum')
data_circ['votos_porcentaje'] = data_circ['votos_cantidad'] / sum_votes
votos_agrup_circ = data_circ.reset_index(drop = True)

# votos_agrup_lista_circ.to_csv('./../datos/out/votos_agrup_lista_circ.csv', index = False)

# votos_agrup_lista_circ = pd.read_csv('./../datos/out/votos_agrup_lista_circ.csv')


### 3. Análisis Exploratorio de Datos (EDA)

#### Resumen Estadístico:
- No se proporciona un resumen estadístico explícito de los datos en el código proporcionado.

#### Visualización de Datos:
- No se incluyen visualizaciones de datos en el código proporcionado.

#### Identificación de Tendencias:
- Se identifican las agrupaciones y listas principales en términos de votos.

In [ ]:
path_datos = '/content/drive/My Drive/electoral/datos'

In [ ]:

# --- Load Data ---
print("Loading data...")

# Load necessary datasets
radio_region = pd.read_csv(path_datos + '/info/radio_ref.csv', usecols=['radio', 'NOMDPTO', 'Region'])
radios_circuitos_secciones = pd.read_csv(path_datos + '/info/radios_circuitos_secciones_ref.csv')[['COD_2010', 'distrito_id', 'seccion_id', 'seccion_nombre']]
prov_nams = pd.read_csv(path_datos + '/BD/distrito_table.csv')

# --- Data Preprocessing ---
print("Processing data...")

# Radio region processing
radio_region['COD_2010'] = radio_region['radio'].astype(str).str.zfill(9)

# Merge data
merge_data = radios_circuitos_secciones.merge(radio_region, on='COD_2010', how='left')
seccion_region = merge_data.drop(['COD_2010', 'radio'], axis=1).drop_duplicates()
seccion_region = seccion_region.groupby(['distrito_id', 'seccion_id', 'seccion_nombre']).first().reset_index()

# Votos agrup processing
votos = votos_agrup_circ
# data_circ_ix = votos.set_index(['distrito_id', 'seccion_id', 'circuito_id', 'eleccion_tag', 'cargo_tag', 'agrupacion_nombre_', 'lista_numero', 'votos_tipo'])
data_circ_ix = votos.set_index(['distrito_id', 'seccion_id', 'circuito_id', 'eleccion_tag', 'cargo_tag', 'agrupacion_nombre_', 'votos_tipo'])
# votos_circuito = data_circ_ix['votos_cantidad'].unstack(['eleccion_tag', 'cargo_tag', 'votos_tipo', 'agrupacion_nombre_', 'lista_numero'])['PASO23n']['PR'].sum(1).sort_values(ascending=False)
votos_circuito = data_circ_ix['votos_cantidad'].unstack(['eleccion_tag', 'cargo_tag', 'votos_tipo', 'agrupacion_nombre_'])['GRAL23n']['PR'].sum(1).sort_values(ascending=False)
circuitos_ppales = votos_circuito[votos_circuito > 1000].index.to_frame().reset_index(drop=True)

# Lista processing
# votos_lista = votos.groupby(['eleccion_tag', 'votos_tipo', 'agrupacion_nombre_', 'lista_numero'])['votos_cantidad'].sum().sort_values(ascending=False)
votos_lista = votos.groupby(['eleccion_tag', 'votos_tipo', 'agrupacion_nombre_'])['votos_cantidad'].sum().sort_values(ascending=False)

N = 20
main_listas = votos_lista.head(N).index.to_frame().reset_index(drop=True)
display(main_listas)

# --- Merge Information ---
print("Merging data...")

info = circuitos_ppales.merge(votos)
info = main_listas.merge(info)
info = info.merge(prov_nams).merge(seccion_region, how='left')

info.head()


### 4. Modelado e Inferencia

#### Selección de Modelo:
- Se implementa un modelo de inferencia ecológica, aunque no se especifica el modelo exacto o la justificación de su elección.

#### Ajuste de Modelo:
- Se realizan cálculos y transformaciones en los datos demográficos y de votación para prepararlos para el análisis de inferencia ecológica.

#### Evaluación de Modelo:
- No se proporciona una evaluación explícita del modelo en el código proporcionado.

#### Inferencias:
- Se realizan inferencias sobre los resultados de votación, aunque no se detallan explícitamente las conclusiones o interpretaciones.

### 5. Interpretación de Resultados

### 6. Visualización de Resultados